###################################
# Dataset Configuration
###################################
features:
  - CRIM
  - ZN
  - INDUS
  - CHAS
  - NOX
  - RM
  - AGE
  - DIS
  - RAD
  - TAX
  - PTRATIO
  - B
  - LSTAT
target: mdev

problem_type: classification 
###################################
# REGRESSION model selection  
###################################

# linear_regression:
#   fit_intercept: True 
#   normalize: False

# random_forest_regression:
#   n_estimators: 101
#   random_state: 7

# neural_net:
#   architecture:
#   - activation: relu
#     nodes: 4
#   - activation: relu
#     nodes: 2
#   - activation: relu
#     nodes: 2
#   - activation: relu
#     nodes: 1

#   optimizer:
#     loss: mse
#     learning_rate: 0.01
#     metrics:
#     - mse
#     - mae

#   training:
#     epochs: 50
#     batch_size: 128

###################################
# CLASSIFICATION model selection 
###################################

# logistic_regression:
#   class_weight: None
#   random_state: 7

# random_forest_classifier:
#   n_estimators: 100
#   class_weight: balanced
#   random_state: 7

neural_net:
  architecture:
  - activation: relu
    nodes: 4
  - activation: relu
    nodes: 2
  - activation: relu
    nodes: 2
  - activation: sigmoid
    nodes: 1

  optimizer:
    loss: binary_crossentropy
    learning_rate: 0.01
    metrics: 
    - accuracy

  training:
    epochs: 50
    batch_size: 128