# ====================================
# Dataset Configuration
# ====================================

features:
- feature_0
- feature_1
- etc... 
target: target

problem_type: regression

train_ratio: 0.70
validation_ratio: 0.15
test_ratio: 0.15

# ====================================
# REGRESSION model selection  
# ====================================

# linear_regression:
#   fit_intercept: True 
#   normalize: False

# random_forest_regression:
#   n_estimators: 101
#   random_state: 7

neural_net:
  architecture:
  - activation: relu
    nodes: 16
  - activation: relu
    nodes: 16
  - activation: relu
    nodes: 8
  - activation: relu
    nodes: 1

  optimizer:
    loss: mse
    learning_rate: 0.001
    metrics:
    - mse
    - mae
    - mape

  training:
    epochs: 200
    batch_size: 32

# ====================================
# CLASSIFICATION model selection 
# ====================================

# logistic_regression:
#   class_weight: None
#   random_state: 7

# random_forest_classifier:
#   n_estimators: 101
#   class_weight: balanced
#   random_state: 7

# neural_net:
#   architecture:
#   - activation: relu
#     nodes: 32
#   - activation: relu
#     nodes: 32
#   - activation: relu
#     nodes: 8
#   - activation: sigmoid
#     nodes: 1

#   optimizer:
#     loss: binary_crossentropy
#     learning_rate: 0.1
#     metrics: 
#     - accuracy

#   training:
#     epochs: 150
#     batch_size: 256