###################################
# Dataset Configuration
###################################
features:
  - CRIM
  - ZN
  - INDUS
  - CHAS
  - NOX
  - RM
  - AGE
  - DIS
  - RAD
  - TAX
  - PTRATIO
  - B
  - LSTAT
target: mdev

###################################
# Which models to use for training
###################################
active_model: neural_net

regression:

  linear_regression:
    fit_intercept: True 
    normalize: False

  random_forest_regression:
    n_estimators: 100

classification:
  random_forest
  neural_net


###################################
# Neural Network Architecture 
###################################
architecture:
- activation: relu
  nodes: 4
- activation: relu
  nodes: 2
- activation: relu
  nodes: 2
- activation: relu
  nodes: 1

optimizer:
  loss: 'mse'

training:
  epochs: 50
  batch_size: 128