###################################
# Dataset Configuration
###################################
features:
- feat_0
- feat_1
target: target


# features:
#   - CRIM
#   - ZN
#   - INDUS
#   - CHAS
#   - NOX
#   - RM
#   - AGE
#   - DIS
#   - RAD
#   - TAX
#   - PTRATIO
#   - B
#   - LSTAT
# target: mdev

# features:
# - '4046'
# - '4225'
# - '4770'
# - Total Volume
# - Total Bags
# - Small Bags
# - Large Bags
# - XLarge Bags
# target: AveragePrice

problem_type: classification

###################################
# REGRESSION model selection  
###################################

# linear_regression:
#   fit_intercept: True 
#   normalize: False

# random_forest_regression:
#   n_estimators: 101
#   random_state: 7

# neural_net:
#   architecture:
#   - activation: relu
#     nodes: 2
#   - activation: relu
#     nodes: 1

#   optimizer:
#     loss: mse
#     learning_rate: 0.01
#     metrics:
#     - mse
#     - mae

#   training:
#     epochs: 150
#     batch_size: 128
#     validation_split: 0.2

###################################
# CLASSIFICATION model selection 
###################################

# logistic_regression:
#   class_weight: None
#   random_state: 7

# random_forest_classifier:
#   n_estimators: 100
#   class_weight: balanced
#   random_state: 7

neural_net:
  architecture:
  - activation: relu
    nodes: 16
  - activation: relu
    nodes: 4
  - activation: sigmoid
    nodes: 1

  optimizer:
    loss: binary_crossentropy
    learning_rate: 0.3
    metrics: 
    - accuracy

  training:
    epochs: 150
    batch_size: 1024
    validation_split: 0.2