features:
- CRIM
- ZN
- INDUS
- CHAS
- NOX
- RM
- AGE
- DIS
- RAD
- TAX
- PTRATIO
- B
- LSTAT
target: mdev
problem_type: classification
random_forest_classifier:
  n_estimators: 100
  class_weight: balanced
  random_state: 7
