features:
- CRIM
- ZN
- INDUS
- CHAS
- NOX
- RM
- AGE
- DIS
- RAD
- TAX
- PTRATIO
- B
- LSTAT
target: mdev
problem_type: classification
neural_net:
  architecture:
  - activation: relu
    nodes: 4
  - activation: relu
    nodes: 2
  - activation: relu
    nodes: 2
  - activation: sigmoid
    nodes: 1
  optimizer:
    loss: binary_crossentropy
    learning_rate: 0.01
    metrics:
    - accuracy
  training:
    epochs: 50
    batch_size: 128
