########################################################################################
#
#
#
#
#
#
########################################################################################


project_name: 'dummy_project'
training_data: 'regression/data/dummy.csv'
features:
  - x1
  - x2
target:
  - y