features:
- CRIM
- ZN
- INDUS
- CHAS
- NOX
- RM
- AGE
- DIS
- RAD
- TAX
- PTRATIO
- B
- LSTAT
target: mdev
architecture:
- activation: relu
  nodes: 2
- activation: relu
  nodes: 1
optimizer:
  loss: mse
training:
  epochs: 200
  batch_size: 16
