features:
- CRIM
- ZN
- INDUS
- CHAS
- NOX
- RM
- AGE
- DIS
- RAD
- TAX
- PTRATIO
- B
- LSTAT
target: mdev
active_model: linear_regression
regression:
  linear_regression:
    fit_intercept: true
    normalize: false
  random_forest_regression:
    n_estimators: 100
classification: random_forest neural_net
architecture:
- activation: relu
  nodes: 2
- activation: relu
  nodes: 1
optimizer:
  loss: mse
training:
  epochs: 50
  batch_size: 16
